name: VitalBack
version: @version@
main: com.tamrielnetwork.vitalback.VitalBack
api-version: 1.17
authors: [ Tamriel Network ]
website: https://tamriel.site
description: Gives players the ability to teleport back to their last location.
commands:
  vitalback:
    description: "Main command"
    usage: "/vitalback"
permissions:
  vitalback.back:
    description: "Permission to teleport back to last location"
    default: op
  vitalback.back.ondeath:
    description: "Permission to teleport back to last location on death"
    default: op